CREATE OR REPLACE TABLE EXA_DB.COUNTY (
    ID int IDENTITY PRIMARY KEY,
    "NAME" VARCHAR(30),
    POPULATION int,
    STATEID int,

    CONSTRAINT FK_QUERY
       FOREIGN KEY (STATEID)
       REFERENCES EXA_DB."STATE"(ID)
);