CREATE OR REPLACE TABLE EXA_DB.QUERY_CATEGORY (
    ID int IDENTITY PRIMARY KEY,
    CATEGORY VARCHAR(50),
    QUERYID int,

    CONSTRAINT FK_QUERY
       FOREIGN KEY (QUERYID)
       REFERENCES EXA_DB.URLDIM(ID)
);